### ISSUE TITLE
Wrapper for CURD feature

### ISSUE THREAD

**Issue by jamestang12** [Silver-Ape/web-back-end#10]
# Implants CURD for auth, authors, paper and users
- [x] [Set up routes and controller for auth table #8](https://github.com/Silver-Ape/web-back-end/issues/8)
- [x] [Set up routes and controller for authors table #7](https://github.com/Silver-Ape/web-back-end/issues/7)
- [x] [Set up routes and controller for paper table #5](https://github.com/Silver-Ape/web-back-end/issues/5)
- [x] [Set up routes and controller for user table #4](https://github.com/Silver-Ape/web-back-end/issues/4)

**Comment by jamestang12** [comment]
All done
